In [57]:
import time
import numpy as np

# Fast Computation of NumPy array

In [230]:
a=[1,2,3,4]

In [213]:
b=[4,5,6]

In [214]:
for i in range(len(a)):
    print(a[i]+b[i])

5
7
9


In [231]:
c=np.array(a)

In [217]:
d=np.array(b)

In [207]:
# Using normal way to compute mean

start=time.time()

#a=sum(x)/len(x)
a=sum(x)/len(x)


print('The timetaken is', time.time()-start)

The timetaken is 9.375622272491455


C:\Users\Admin\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in long_scalars
  


In [211]:
# Using numpy to compute mean

start=time.time()

b=np.mean(x)

print('The timetaken is', time.time()-start)

The timetaken is 0.13392186164855957


## Creating numpy arrays


_1. Using regular Python lists_



In [240]:
# 1. Using regular Python lists
# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# Let's print the ndarray we just created using the print() command
print('x = ', x)


x =  [1 2 3 4 5]


In [241]:
# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))


x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>


In [88]:
#np.eye(5)

In [92]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

print(Y)

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


## Accessing elements in 1D Numpy Array - Indexing



In [94]:
countries=np.array(['India','US','UK','Canada','Aus','Middle East'])

# Let's access some elements with indices
print('This is First Element in countries:', countries[0]) 
print('This is Second Element in countries:', countries[1])
print('This is all Elements from fourth position in countries:', countries[4:])
print()


This is First Element in countries: India
This is Second Element in countries: US
This is all Elements from fourth position in countries: ['Aus' 'Middle East']



## Accessing elements in 2D Numpy Array - Indexing



In [157]:
countries_1=np.array([['India','US','UK'],['Canada','Aus','Middle East']])

# Let's access some elements with indices
print('This is First Element in countries:', countries_1[0]) 
print('This is Second Element in countries:', countries_1[1])
print('This is all Elements from fourth position in countries:', countries_1[1][1])

#There is one more way of accessing 2D arrays


This is First Element in countries: ['India' 'US' 'UK']
This is Second Element in countries: ['Canada' 'Aus' 'Middle East']
This is all Elements from fourth position in countries: Aus


In [97]:
countries_1

array([['India', 'US', 'UK'],
       ['Canada', 'Aus', 'Middle East']], dtype='<U11')

In [98]:
countries_1[1,1]

'Aus'

In [99]:
countries_1[1,2]

'Middle East'

## Modifying elements in Array



In [110]:
countries_1[1,1]='Eng'
print(countries_1)

[['India' 'US' 'UK']
 ['Canada' 'Eng' 'Middle East']]


In [115]:
countries_1[1][1]='England'
print(countries_1)

[['India' 'US' 'UK']
 ['Canada' 'England' 'Middle East']]


In [116]:
countries_1

array([['India', 'US', 'UK'],
       ['Canada', 'England', 'Middle East']], dtype='<U11')

## Boolean operations
### Filtering records


In [188]:
experience = np.array([10,7,15,8,9,6,12,4])
experience

array([10,  7, 15,  8,  9,  6, 12,  4])

In [189]:
experience > 10

array([False, False,  True, False, False, False,  True, False])

In [191]:
experience[experience > 10]

array([15, 12])

## Numpy Exercise 1

**Let there be 2 arrays which hold the employees time in office information and employee_id in 2 separate arrays. Find the employee ids whose time in office is less than the average office hours of employees**

In [178]:
# time_in_office of employees

time_in_office=np.array([8,6.5,5.5,8,9,7.5,5,8.5,6.5,7,6.5,10.2,12,8.5,10.5,9.5,7,6,5.5])

In [179]:
# Employee ids (The order of both the arrays is same)
employee_id=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19])

## Numpy Exercise 2

**Find the count of employee whose time in office is >= 9 hrs**

In [152]:
# No of employees whose time_in_office is >=9 hrs 

time_in_office=np.array([8,6.5,5.5,8,9,7.5,5,8.5,6.5,7,6.5,10.2,12,8.5,10.5,9.5,7,6,5.5])